# Generated by Django 3.0.5 on 2020-04-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech', '0002_auto_20200415_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all',
            name='startedfrom',
            field=models.DateTimeField(verbose_name='started from'),
        ),
    ]
